### ISSUE TITLE
Translation of Help strings

### ISSUE THREAD

**Issue by meigwilym** [simplethings/SimpleThingsFormExtraBundle#39]
Symfony 2.2:

I've been trying to use translated strings in the form field Help option, but without success. 

My first attempt was to try what the documentation said, and added 
- SimpleThingsFormExtraBundle:Form:translation_domain.html.twig

under twig.form.resources in config.yml, and set the 'translation_domain' option to 'form_extra' in $builder->add() in my form type. I also created form_type.yml in Resources/translations with the necassary strings. 

This throws the following error

```
 The function "_form_is_choice_group" does not exist in SimpleThingsFormExtraBundle:Form:translation_domain.html.twig at line 6
```

I've looked into this but it took me nowhere. 

To get it working, I removed all of this and edited field_type_help.html.twig to the following:

```
<span class="help">{{ help|trans }}</span>
```

This works fine. 

Am I doing something wrong? Or shall I fork and create a pull request to add this feature.

Danke!

**Comment by stof** [comment]
The translation domain stuff provided in this bundle is not meant to be used in Symfony 2.2 but only in Symfony 2.0. The support of translation domains is a core feature since 2.1
