### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by pulzarraider** [simplethings/SimpleThingsFormExtraBundle#50]
Can you please release new version of this bundle (tag the current master)?

Latest stable version is one year old.

**Comment by pulzarraider** [comment]
ping @DavidBadura

**Comment by pulzarraider** [comment]
ping @beberlei @tolry @hnadler

**Comment by DavidBadura** [comment]
:smile: done :wink:

**Comment by pulzarraider** [comment]
@DavidBadura Thank you very much.
