### ISSUE TITLE
Could not load type "recaptcha"

### ISSUE THREAD

**Issue by cursedcoder** [simplethings/SimpleThingsFormExtraBundle#9]
When I add the recaptcha field in builder, there show this error.

Symfony\Component\Form\Exception\FormException: Could not load type "recaptcha" (uncaught exception) at C:\symfony\vendor\symfony\src\Symfony\Component\Form\FormFactory.php line 375

**Comment by stof** [comment]
The name of the type is `formextra_recaptcha`, not `recaptcha`

**Comment by cursedcoder** [comment]
Okay, but in readme given "recaptcha"

Usage
RecaptchaFieldType
<?php
// ...
$builder->add('recaptcha', 'recaptcha');
// ...

fix it plz.

**Comment by stof** [comment]
I cannot fix it. I don't have push access here.

**Comment by beberlei** [comment]
Fixed in GH-17, closing this.
